---
micronaut:
    application:
        name: multitenancy
    server:
        port: 8080

endpoints:
    beans:
        enabled: true
        sensitive: false
---
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
dataSource:
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''

grails:
  gorm:
    multiTenancy:
      mode: DISCRIMINATOR
      tenantResolverClass: multitenancy.SubDomainTenantResolver